### PR TITLE
make it java11 compatible

### PR DESCRIPTION
**Pull request by erwindon**
see #142

### CODE REVIEW

**Comment by erwindon** [comment]
@petternordlander 
the files in `src/deb` indicate the build of a Debian package, but it looks incomplete.
I just updated the `Depends:` clause in `src/deb/control/control` to include all currently known/suitable java-runtimes, i.e. 11 through 21
how can I test that?

**Comment by erwindon** [comment]
That is very useful information on the context.
I have enough knowledge on Debian style packages to get this working. Already created a local Debian VM in VirtualBox for this.
I'll just add a few practical changes in this PR to be able to actually create a deb package, install it locally and run it.

**Comment by erwindon** [comment]
no matter how popular the debian package of 'a' might become, the name 'a' as package name is never allowed. see https://www.debian.org/doc/debian-policy/ch-controlfields.html, where section 5.6.1 states that "[package names] must be at least two characters long and must start with an alphanumeric character."
I'll use 'fmtn-a' as debian package name (but feel free to suggest an even better one!)

**Comment by erwindon** [comment]
I took one Debian specific file out of the first commit.

The second commit has all the Debian specific stuff in it:
* added script to build the DEB package; and
* fixed shell script (original name bin.sh, now a.sh) to start `a`; and
* moved file `control` to proper location; filled the placeholders that it still had; and
* set the package dependencies to java11+; the headless edition is sufficient; and
* verified by building+installing the package --> Unix command `a` now shows the usage-text.

**Comment by erwindon** [comment]
@northlander
(when) do you have time to review this?

**Comment by northlander** [comment]
Awesome work @erwindon !

**Pull request merged**
